### ISSUE TITLE
Logic unclear

### ISSUE THREAD

**Issue by eford** [blhendricks/project-blhendricks#7]
https://github.com/blhendricks/project-blhendricks/blob/d1e5316601c37a1c7b691cf79daeb5cac368d36b/Event_Generator.jl#L51
Why +1?

**Comment by blhendricks** [comment]
This is to check whether this is the final batch! It doesn't make sense in this iteration actually because the for loop is going over the wrong array... I should have been going through starting at 0 rather than 1, which makes the +1 necessary, but I was starting at 1 by accident (which caused several other issues that have since been fixed).
